import type {
  ContextEvidence,
  Dataset,
  EvaluationReport,
  EvaluationTask,
  ExecutionSnapshot,
  ProjectOverview,
  SampleDiagnosis,
  SampleSummary,
} from '../types';

export const DEMO_PROJECT_ID = 'demo';
export const DEMO_TASK_ID = 'eval-20260826';
export const DEMO_SAMPLE_ID = 'sample-042';

const executionSnapshot: ExecutionSnapshot = {
  contractVersion: '2.0',
  adapterId: 'mock',
  providerId: null,
  prompt: {
    version: 'support-rag@v12',
    text: '仅依据给定上下文回答；证据不足时明确说明。',
  },
  generation: {
    model: 'mock-ragops-v1',
    temperature: 0,
    topP: 1,
    maxOutputTokens: 512,
    stop: [],
    seed: null,
  },
  contextPolicy: 'dataset_contexts',
  dataset: {
    id: 'ds-support-golden',
    version: 'v3.4',
    schemaVersion: '2.0',
    contentSha256: 'fixture-only-not-a-production-hash',
  },
  metricConfig: [],
  qualityGate: null,
  externalCallsEnabledAtCreation: false,
  createdAt: '2026-08-26T09:20:00+08:00',
  configVersion: 'fixture-config-v2',
};

export const evaluationTasks: EvaluationTask[] = [
  {
    id: DEMO_TASK_ID,
    name: '客服知识库 v3 回归评测',
    datasetId: 'ds-support-golden',
    datasetName: '客服黄金问答集',
    status: 'completed',
    outcome: 'succeeded',
    qualityStatus: 'not_evaluated',
    qualityVerdict: 'unknown',
    qualityScore: null,
    progress: 100,
    createdAt: '2026-08-26T09:20:00+08:00',
    completedAt: '2026-08-26T09:27:42+08:00',
    modelVersion: 'mock-ragops-v1',
    promptVersion: 'support-rag@v12',
    adapterId: 'mock',
    providerId: null,
    isMock: true,
    totalSamples: 3,
    succeededSamples: 3,
    failedSamples: 0,
    schemaVersion: '2.0',
    executionSnapshot,
  },
  {
    id: 'eval-20260825',
    name: 'Rerank 参数 A/B 基线',
    datasetId: 'ds-support-golden',
    datasetName: '客服黄金问答集',
    status: 'running',
    outcome: null,
    qualityStatus: 'not_evaluated',
    qualityVerdict: 'unknown',
    qualityScore: null,
    progress: 68,
    createdAt: '2026-08-26T08:45:00+08:00',
    completedAt: null,
    modelVersion: 'mock-ragops-v1',
    promptVersion: 'support-rag@v12',
    adapterId: 'mock',
    providerId: null,
    isMock: true,
    totalSamples: 3,
    succeededSamples: 2,
    failedSamples: 0,
    schemaVersion: '2.0',
    executionSnapshot,
  },
  {
    id: 'eval-20260824',
    name: '模拟执行失败样本',
    datasetId: 'ds-billing-edge',
    datasetName: '账单边界样本',
    status: 'failed',
    outcome: 'failed',
    qualityStatus: 'not_evaluated',
    qualityVerdict: 'unknown',
    qualityScore: null,
    progress: 100,
    createdAt: '2026-08-25T17:30:00+08:00',
    completedAt: '2026-08-25T17:31:00+08:00',
    modelVersion: 'mock-ragops-v1',
    promptVersion: 'billing-rag@v7',
    adapterId: 'mock',
    providerId: null,
    isMock: true,
    totalSamples: 2,
    succeededSamples: 0,
    failedSamples: 2,
    schemaVersion: '2.0',
    executionSnapshot: { ...executionSnapshot, dataset: { ...executionSnapshot.dataset, id: 'ds-billing-edge', version: 'v1.8' } },
  },
];

export const datasets: Dataset[] = [
  {
    id: 'ds-support-golden',
    name: '客服黄金问答集',
    description: '人工构造的退款、物流、会员与售后政策离线样本。',
    sampleCount: 3,
    status: 'ready',
    schemaVersion: '2.0',
    version: 'v3.4',
    contentSha256: 'fixture-only-not-a-production-hash',
    coverage: 94,
    updatedAt: '2026-08-25T16:40:00+08:00',
    owner: '质量平台组',
  },
  {
    id: 'ds-billing-edge',
    name: '账单边界样本',
    description: '人工构造的账期切换、退款抵扣与跨币种场景。',
    sampleCount: 2,
    status: 'ready',
    schemaVersion: '2.0',
    version: 'v1.8',
    contentSha256: 'fixture-only-billing-hash',
    coverage: 81,
    updatedAt: '2026-08-24T11:15:00+08:00',
    owner: '计费产品组',
  },
  {
    id: 'ds-new-policy',
    name: '新政策增量集',
    description: '待完成标注审核的人工构造政策增量。',
    sampleCount: 1,
    status: 'draft',
    schemaVersion: '2.0',
    version: 'v0.3',
    contentSha256: null,
    coverage: 47,
    updatedAt: '2026-08-26T10:08:00+08:00',
    owner: '知识运营组',
  },
];

export const projectOverview: ProjectOverview = {
  project: {
    id: DEMO_PROJECT_ID,
    name: '客服 RAG 生产线',
    description: '使用人工样本与模拟执行器演示质量评测和故障诊断链路',
    environment: 'offline-fixture',
    updatedAt: '2026-08-26T09:28:00+08:00',
  },
  metrics: [
    { key: 'execution_success_rate', label: '执行成功率', value: 100, status: 'ok', unit: '%' },
    { key: 'quality_score', label: '质量分', value: null, status: 'not_evaluated' },
    { key: 'recall_at_5', label: '检索 Recall@5', value: null, status: 'not_evaluated' },
    { key: 'token_usage', label: 'Token 用量', value: null, status: 'unknown' },
    { key: 'cost', label: '成本', value: null, status: 'unknown', unit: 'USD' },
  ],
  recentTasks: evaluationTasks,
  failureDistribution: [
    { key: 'retrieval_missing', label: '模拟：检索缺失', count: 1, severity: 'critical' },
    { key: 'citation_conflict', label: '模拟：引用冲突', count: 1, severity: 'warning' },
  ],
  trend: [],
  warnings: ['当前为离线 fixture：没有真实提供方连接，也没有执行语义质量评估。'],
};

const contexts: ContextEvidence[] = [
  {
    key: 'retrieved:1:doc-legacy-faq',
    origin: 'retrieved',
    rank: 1,
    rankBefore: null,
    retrievalRunId: 'retrieval-fixture-042',
    docId: 'doc-legacy-faq',
    chunkId: 'chunk-8841',
    evidenceIds: ['evidence-legacy'],
    title: '会员成长值常见问题（2024 归档）',
    source: 'fixture://membership/archive/faq-2024',
    score: 0.83,
    relevanceGrade: 1,
    usefulness: false,
    isExpected: false,
    text: '特殊退款场景下，成长值最迟于 7 个工作日完成调整。具体方式以当期规则为准。',
  },
  {
    key: 'retrieved:2:doc-refund-general',
    origin: 'retrieved',
    rank: 2,
    rankBefore: null,
    retrievalRunId: 'retrieval-fixture-042',
    docId: 'doc-refund-general',
    chunkId: 'chunk-2190',
    evidenceIds: ['evidence-refund'],
    title: '订单退款通用规则',
    source: 'fixture://orders/refund/general',
    score: 0.78,
    relevanceGrade: 2,
    usefulness: true,
    isExpected: false,
    text: '部分退款时，积分、优惠与成长值均按退款商品金额比例调整，不影响未退款商品对应权益。',
  },
  {
    key: 'retrieved:9:doc-policy-2026',
    origin: 'retrieved',
    rank: 9,
    rankBefore: null,
    retrievalRunId: 'retrieval-fixture-042',
    docId: 'doc-policy-2026',
    chunkId: 'chunk-9027',
    evidenceIds: ['evidence-policy-2026'],
    title: '会员成长值规则（2026 生效）',
    source: 'fixture://membership/policy/2026',
    score: 0.49,
    relevanceGrade: 3,
    usefulness: true,
    isExpected: true,
    text: '退款成功后 24 小时内，按退款商品实付金额占订单实付金额的比例扣回成长值。',
  },
];

const sampleSummary = (overrides: Partial<SampleSummary>): SampleSummary => ({
  id: DEMO_SAMPLE_ID,
  sampleId: DEMO_SAMPLE_ID,
  question: '会员退款后，已发放的成长值会如何处理？',
  referenceAnswer: '退款成功后，订单产生的成长值将在 24 小时内按退款商品金额比例扣回；部分退款只扣回对应部分。',
  historicalAnswer: '旧系统记录：退款后等待系统调整。',
  generatedAnswer: '[mock] 退款成功后，成长值通常会在 7 个工作日内全部清零 [1]。',
  failureType: '关键证据未进入 Top 5',
  severity: 'critical',
  recallAt5: 0,
  recallAt5Status: 'ok',
  faithfulness: null,
  faithfulnessStatus: 'not_evaluated',
  citationSupportRate: null,
  citationSupportStatus: 'not_evaluated',
  latencyMs: 0,
  runStatus: 'succeeded',
  qualityStatus: 'not_evaluated',
  reviewStatus: 'pending',
  contexts,
  citations: [
    {
      id: 'citation-1',
      marker: '[1]',
      claimId: 'claim-1',
      raw: '[1]',
      targetType: 'document',
      targetId: 'doc-legacy-faq',
      resolved: true,
      supportsClaim: null,
      supportJudgeVersion: null,
    },
    {
      id: 'citation-2',
      marker: '[2]',
      claimId: 'claim-2',
      raw: '[2]',
      targetType: 'document',
      targetId: 'doc-refund-general',
      resolved: true,
      supportsClaim: false,
      supportJudgeVersion: 'fixture-human-label-v1',
    },
  ],
  error: null,
  isMock: true,
  ...overrides,
});

const reportSamples: SampleSummary[] = [
  sampleSummary({}),
  sampleSummary({
    id: 'sample-017', sampleId: 'sample-017', question: '跨境订单退货的运费由谁承担？',
    referenceAnswer: '按人工构造政策标签处理。', historicalAnswer: null, generatedAnswer: '[mock] 请以给定上下文为准。',
    failureType: '上下文污染', severity: 'warning', recallAt5: 0.8, reviewStatus: 'confirmed', contexts: [], citations: [],
  }),
  sampleSummary({
    id: 'sample-088', sampleId: 'sample-088', question: '电子发票的抬头可以修改几次？',
    referenceAnswer: null, historicalAnswer: null, generatedAnswer: '[mock] 上下文未提供该信息。',
    failureType: '引用缺失', severity: 'warning', recallAt5: null, recallAt5Status: 'not_evaluated', contexts: [], citations: [],
  }),
];

export const report: EvaluationReport = {
  id: 'report-20260826',
  schemaVersion: '2.0',
  task: evaluationTasks[0],
  verdict: 'undetermined',
  verdictReason: '模拟任务执行成功；未配置质量门且语义指标未执行，质量结论保持未知。',
  executionSummary: { outcome: 'succeeded', totalCount: 3, succeededCount: 3, failedCount: 0, successRate: 1 },
  qualitySummary: { status: 'not_evaluated', verdict: 'unknown', score: null, evaluatedSampleCount: 0 },
  executionSnapshot,
  isSimulated: true,
  generatedAt: '2026-08-26T09:28:00+08:00',
  baselineLabel: null,
  metrics: [
    { key: 'execution_success_rate', label: '执行成功率', value: 1, status: 'ok', evaluatedCount: 3, excludedCount: 0 },
    { key: 'recall_at_5', label: '检索 Recall@5', value: null, status: 'not_evaluated', details: { context_origin: 'provided' } },
    { key: 'citation_resolution_rate', label: '引用解析率', value: 1, status: 'ok', evaluatedCount: 2, excludedCount: 0 },
    { key: 'citation_support_rate', label: '引用支持率', value: null, status: 'not_evaluated' },
  ],
  failures: projectOverview.failureDistribution,
  samples: reportSamples,
  warnings: ['SIMULATED：报告来自仓库内人工 fixture，不代表真实模型、真实检索或真实连接验证。'],
};

export const diagnosis: SampleDiagnosis = {
  id: DEMO_SAMPLE_ID,
  sampleId: DEMO_SAMPLE_ID,
  taskId: DEMO_TASK_ID,
  question: reportSamples[0].question,
  expectedAnswer: reportSamples[0].referenceAnswer,
  historicalAnswer: reportSamples[0].historicalAnswer,
  generatedAnswer: reportSamples[0].generatedAnswer,
  metrics: [
    { key: 'recall_at_5', label: 'Recall@5', value: 0, status: 'ok' },
    { key: 'faithfulness', label: '答案忠实性', value: null, status: 'not_evaluated' },
    { key: 'citation_resolution_rate', label: '引用解析率', value: 1, status: 'ok' },
    { key: 'citation_support_rate', label: '引用支持率', value: null, status: 'not_evaluated' },
  ],
  qualityStatus: 'not_evaluated',
  primaryDiagnosis: {
    label: '关键政策文档未进入 Top 5',
    confidence: 0.94,
    severity: 'critical',
    explanation: '人工 fixture 标记期望文档位于第 9 位；这是离线诊断示例，不是一次真实检索证明。',
    evidenceIds: ['doc-legacy-faq', 'doc-policy-2026'],
  },
  secondaryDiagnoses: [
    {
      label: '引用证据与结论冲突',
      confidence: 0.88,
      severity: 'warning',
      explanation: 'fixture 中引用 [2] 的人工支持性标签为 false；解析成功本身不作为支持性证明。',
      evidenceIds: ['doc-refund-general'],
    },
  ],
  contexts,
  citations: reportSamples[0].citations,
  run: {
    runId: 'run-fixture-042',
    status: 'succeeded',
    adapterId: 'mock',
    providerId: null,
    requestedModel: 'mock-ragops-v1',
    actualModel: 'mock-ragops-v1',
    isMock: true,
    finishReason: 'stop',
    latencyMs: 0,
    usage: null,
    cost: null,
    providerRequestId: null,
    attemptCount: 1,
    error: null,
    startedAt: '2026-08-26T09:27:31+08:00',
    finishedAt: '2026-08-26T09:27:31+08:00',
  },
  reviewStatus: 'pending',
  traceId: 'run-fixture-042',
  evaluatedAt: '2026-08-26T09:27:31+08:00',
  warnings: ['SIMULATED：上下文、回答、引用和诊断均为人工构造 fixture。'],
};
