import type {
  Dataset,
  EvaluationReport,
  EvaluationTask,
  ProjectOverview,
  SampleDiagnosis,
} from '../types';

export const DEMO_PROJECT_ID = 'demo';
export const DEMO_TASK_ID = 'eval-20260826';
export const DEMO_SAMPLE_ID = 'sample-042';

export const evaluationTasks: EvaluationTask[] = [
  {
    id: DEMO_TASK_ID,
    name: '客服知识库 v3 回归评测',
    datasetId: 'ds-support-golden',
    datasetName: '客服黄金问答集',
    status: 'completed',
    progress: 100,
    createdAt: '2026-08-26T09:20:00+08:00',
    completedAt: '2026-08-26T09:27:42+08:00',
    modelVersion: 'qwen3-32b@2026-08',
    promptVersion: 'support-rag@v12',
    totalSamples: 120,
    failedSamples: 18,
    score: 82.4,
  },
  {
    id: 'eval-20260825',
    name: 'Rerank 参数 A/B 基线',
    datasetId: 'ds-support-golden',
    datasetName: '客服黄金问答集',
    status: 'running',
    progress: 68,
    createdAt: '2026-08-26T08:45:00+08:00',
    modelVersion: 'qwen3-32b@2026-08',
    promptVersion: 'support-rag@v12',
    totalSamples: 120,
  },
  {
    id: 'eval-20260824',
    name: '账单问答灰度检查',
    datasetId: 'ds-billing-edge',
    datasetName: '账单边界样本',
    status: 'failed',
    progress: 34,
    createdAt: '2026-08-25T17:30:00+08:00',
    modelVersion: 'qwen3-14b@2026-08',
    promptVersion: 'billing-rag@v7',
    totalSamples: 64,
  },
];

export const datasets: Dataset[] = [
  {
    id: 'ds-support-golden',
    name: '客服黄金问答集',
    description: '覆盖退款、物流、会员与售后政策的稳定回归集。',
    sampleCount: 120,
    status: 'ready',
    version: 'v3.4',
    coverage: 94,
    updatedAt: '2026-08-25T16:40:00+08:00',
    owner: '质量平台组',
  },
  {
    id: 'ds-billing-edge',
    name: '账单边界样本',
    description: '账期切换、退款抵扣与跨币种场景。',
    sampleCount: 64,
    status: 'ready',
    version: 'v1.8',
    coverage: 81,
    updatedAt: '2026-08-24T11:15:00+08:00',
    owner: '计费产品组',
  },
  {
    id: 'ds-new-policy',
    name: '新政策增量集',
    description: '待完成标注审核的 2026 Q3 政策增量。',
    sampleCount: 38,
    status: 'draft',
    version: 'v0.3',
    coverage: 47,
    updatedAt: '2026-08-26T10:08:00+08:00',
    owner: '知识运营组',
  },
];

export const projectOverview: ProjectOverview = {
  project: {
    id: DEMO_PROJECT_ID,
    name: '客服 RAG 生产线',
    description: '生产客服助手的离线质量评测与故障诊断项目',
    environment: 'production-shadow',
    updatedAt: '2026-08-26T09:28:00+08:00',
  },
  metrics: [
    { key: 'quality_score', label: '综合质量分', value: 82.4, delta: 2.8, direction: 'higher', threshold: 80 },
    { key: 'recall_at_5', label: 'Recall@5', value: 88.3, unit: '%', delta: 1.2, direction: 'higher', threshold: 85 },
    { key: 'faithfulness', label: '答案忠实性', value: 79.6, unit: '%', delta: -0.7, direction: 'higher', threshold: 80 },
    { key: 'citation_hit', label: '引用命中率', value: 86.7, unit: '%', delta: 4.1, direction: 'higher', threshold: 85 },
    { key: 'p95_latency', label: 'P95 延迟', value: 1840, unit: 'ms', delta: -8.4, direction: 'lower', threshold: 2000 },
  ],
  recentTasks: evaluationTasks,
  failureDistribution: [
    { key: 'retrieval_missing', label: '检索缺失', count: 7, severity: 'critical' },
    { key: 'context_pollution', label: '上下文污染', count: 5, severity: 'warning' },
    { key: 'citation_missing', label: '引用缺失', count: 4, severity: 'warning' },
    { key: 'prompt_weak', label: 'Prompt 约束弱', count: 2, severity: 'warning' },
  ],
  trend: [
    { label: '08-20', score: 76, latencyMs: 2160 },
    { label: '08-21', score: 78, latencyMs: 2050 },
    { label: '08-22', score: 77, latencyMs: 1980 },
    { label: '08-23', score: 80, latencyMs: 1910 },
    { label: '08-24', score: 79, latencyMs: 1870 },
    { label: '08-25', score: 81, latencyMs: 1820 },
    { label: '08-26', score: 82.4, latencyMs: 1840 },
  ],
};

export const report: EvaluationReport = {
  id: 'report-20260826',
  task: evaluationTasks[0],
  verdict: 'passed',
  verdictReason: '综合质量分与核心检索指标达到门禁；答案忠实性低于目标 0.4pp，建议观察。',
  generatedAt: '2026-08-26T09:28:00+08:00',
  baselineLabel: '客服知识库 v2 · prompt v11',
  metrics: projectOverview.metrics,
  failures: projectOverview.failureDistribution,
  samples: [
    {
      id: DEMO_SAMPLE_ID,
      question: '会员退款后，已发放的成长值会如何处理？',
      failureType: '检索缺失',
      severity: 'critical',
      recallAt5: 0,
      faithfulness: 0.62,
      citationHitRate: 0.5,
      latencyMs: 1654,
      reviewStatus: 'pending',
    },
    {
      id: 'sample-017',
      question: '跨境订单退货的运费由谁承担？',
      failureType: '上下文污染',
      severity: 'warning',
      recallAt5: 0.8,
      faithfulness: 0.71,
      citationHitRate: 0.67,
      latencyMs: 2098,
      reviewStatus: 'confirmed',
    },
    {
      id: 'sample-088',
      question: '电子发票的抬头可以修改几次？',
      failureType: '引用缺失',
      severity: 'warning',
      recallAt5: 1,
      faithfulness: 0.82,
      citationHitRate: 0,
      latencyMs: 1430,
      reviewStatus: 'pending',
    },
  ],
};

export const diagnosis: SampleDiagnosis = {
  id: DEMO_SAMPLE_ID,
  taskId: DEMO_TASK_ID,
  question: '会员退款后，已发放的成长值会如何处理？',
  expectedAnswer: '退款成功后，订单产生的成长值将在 24 小时内按退款商品金额比例扣回；部分退款只扣回对应部分。',
  generatedAnswer: '退款成功后，成长值通常会在 7 个工作日内全部清零 [1]。如果是部分退款，系统也会撤销本订单的全部成长值 [2]。',
  metrics: [
    { key: 'recall_at_5', label: 'Recall@5', value: 0, unit: '%', threshold: 85 },
    { key: 'mrr', label: 'MRR', value: 0, threshold: 0.7 },
    { key: 'faithfulness', label: '答案忠实性', value: 62, unit: '%', threshold: 80 },
    { key: 'citation_hit', label: '引用命中率', value: 50, unit: '%', threshold: 85 },
  ],
  primaryDiagnosis: {
    label: '关键政策文档未进入 Top 5',
    confidence: 0.94,
    severity: 'critical',
    explanation: '期望文档“会员成长值规则 2026”未被召回，回答转而使用了过期 FAQ，并产生“全部清零”的错误结论。',
    evidenceIds: ['doc-legacy-faq', 'doc-policy-2026'],
  },
  secondaryDiagnoses: [
    {
      label: '引用证据与结论冲突',
      confidence: 0.88,
      severity: 'warning',
      explanation: '引用 [2] 的原文说明“按金额比例调整”，不能支持“撤销全部成长值”。',
      evidenceIds: ['doc-refund-general'],
    },
  ],
  retrievedDocuments: [
    {
      id: 'doc-legacy-faq',
      rank: 1,
      title: '会员成长值常见问题（2024 归档）',
      source: 'kb://membership/archive/faq-2024',
      score: 0.83,
      isExpected: false,
      snippet: '特殊退款场景下，成长值最迟于 7 个工作日完成调整。具体方式以当期规则为准。',
      chunkId: 'chunk-8841',
    },
    {
      id: 'doc-refund-general',
      rank: 2,
      title: '订单退款通用规则',
      source: 'kb://orders/refund/general',
      score: 0.78,
      isExpected: false,
      snippet: '部分退款时，积分、优惠与成长值均按退款商品金额比例调整，不影响未退款商品对应权益。',
      chunkId: 'chunk-2190',
    },
    {
      id: 'doc-coupon',
      rank: 3,
      title: '优惠券退回说明',
      source: 'kb://promotion/coupon/refund',
      score: 0.66,
      isExpected: false,
      snippet: '优惠券是否退回取决于券类型与有效期，本规则不适用于会员成长值。',
      chunkId: 'chunk-0318',
    },
    {
      id: 'doc-policy-2026',
      rank: 9,
      title: '会员成长值规则（2026 生效）',
      source: 'kb://membership/policy/2026',
      score: 0.49,
      isExpected: true,
      snippet: '退款成功后 24 小时内，按退款商品实付金额占订单实付金额的比例扣回成长值。',
      chunkId: 'chunk-9027',
    },
  ],
  citations: [
    { id: 'citation-1', marker: '[1]', documentId: 'doc-legacy-faq', claim: '7 个工作日内全部清零', supported: false },
    { id: 'citation-2', marker: '[2]', documentId: 'doc-refund-general', claim: '部分退款撤销全部成长值', supported: false },
  ],
  traceId: 'trace-7f13e925a4d2',
  evaluatedAt: '2026-08-26T09:27:31+08:00',
};
